### ISSUE TITLE
Null Reference Exception

### ISSUE THREAD

**Issue by djsmith** [congdongdotnet/GoogleRecaptcha#2]
On our production server we intermittently get this exception:

> System.Web.HttpException (0x80004005): HandlingInstanceID: 5f9639e5-90b7-4f4a-a3e0-0cd57950f925
> An exception of type 'System.NullReferenceException' occurred and was caught.
> 10/22/2015 19:10:41
> Type : System.NullReferenceException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
> Message : Object reference not set to an instance of an object.
> Source : GoogleRecaptchaWebForms
> Help link : 
> Data : System.Collections.ListDictionaryInternal
> TargetSite : Void Validate()
> HResult : -2147467261
> Stack Trace :    at GoogleRecaptchaWebForms.RecaptchaV2Control.Validate()
>    at System.Web.UI.Page.Validate()
>    at System.Web.UI.WebControls.ImageButton.RaisePostBackEvent(String eventArgument)
>    at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

Unfortunately it doesn't happen that often and I've never see it on our dev server or when running localhost. 

Any ideas? Perhaps wrapping a try...catch around the code in the Validate method?

**Comment by 1001binary** [comment]
This issue has been fixed at your commit #3 Recaptcha Validate error handling.
