### ISSUE TITLE
Nuget package

### ISSUE THREAD

**Issue by ksuh999** [congdongdotnet/GoogleRecaptcha#4]
Hi there,

Can you update the nuget package?  I noticed you made a bug fix that I'd like to pull. Thanks.

**Comment by EPinci** [comment]
I'd appreciate it too.
Thank you!

**Comment by 1001binary** [comment]
Hi all,

I upgraded just the _GoogleRecaptcha_ nuget package to latest version [1.2.1](https://www.nuget.org/packages/GoogleRecaptcha/). Please let me know if any problem.

Regards.
