### ISSUE TITLE
Missing javascript reference for WebControl

### ISSUE THREAD

**Issue by EPinci** [congdongdotnet/GoogleRecaptcha#5]
I installed the WebForm library per documentation and made the implementation.
The control gets rendered as DIV on the page but no javascript to the google code is inserted and the recaptcha does not get displayed.
I fixed it by manually adding the required
`<script src='https://www.google.com/recaptcha/api.js'></script>`
on the page.
I would say either render it right after the actual control's DIV or update the documentation to manually include it.

Thank you!

**Comment by 1001binary** [comment]
Hi EPinci,

I just updated the documentation.

Regards.

**Comment by jerrychoubear** [comment]
Same with the MVC one, no reCaptcha image shown as I can see the DIV does get rendered on the page,
and everything is ok after adding the js:
 `<script src='https://www.google.com/recaptcha/api.js'></script>`
