### ISSUE TITLE
validate failure after choose matched pic several times

### ISSUE THREAD

**Issue by liz-in** [congdongdotnet/GoogleRecaptcha#8]
Hi,

In the beginning, signing into the website just checked the "I am not robot".

When I login several times, GoogleRecaptcha starts ask me for choosing matched pic.
I choose and post the login form, it always reply failure of googlerecaptcha.

I don't know why it always shows the result. Could you help me ?

**Comment by 1001binary** [comment]
I think that maybe your secret key was incorrect. Could you please check it on your server-side code again?
